### ISSUE TITLE
Fix breakage on Python 3.10

### ISSUE THREAD

**Issue by mdickinson** [mdickinson/refcycle#83]
We have some imports from `collections` that should be imports from `collections.abc`; these break on Python 3.10 and Python 3.11.

**Comment by coyotelll** [comment]
Hi we are also seeing this issue:
File "/usr/local/lib/python3.10/dist-packages/refcycle/key_transform_dict.py", line 27, in <module>
    class KeyTransformDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

Do you have a plan to fix this? Thanks.

**Comment by mdickinson** [comment]
@coyotelll It's fixed in the latest release, which I've just pushed to PyPI: https://pypi.org/project/refcycle/0.3.0/
